
name: 'dbt_analytics'
version: '1.0.0'
config-version: 2

profile: 'dbt_analytics'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +query_tag: dbt_deel
  +persist_docs:
    relation: true
    columns: true
  dbt_analytics:

    staging:
      +materialized: table # as a view to avoid redundancy on de data sources
      +schema: staging

    marts:
      +materialized: table
      warehouse:
        +schema: warehouse
      reporting:
        +schema: reporting
      intermediate:
        +schema: intermediate