# File: my_project/models/dim_countries.yml

version: 2


models:
  - name: rpt_globepay
    description: >
      This model is for reporting purposes, it already has different joins to be able to filter at different granularities,
      and all the data is related to the acceptance and chargebak reports of the Globepay platform.
    columns:
          - name: _date_time
            description: "date time when the transaction was created"
          - name: _hour
            description: "Hour time when the transaction was created "
          - name: _date_day
            description: "date Day when the transaction was created "
          - name: month
            description: "Month when the transaction was created "
          - name: week
            description: "Month when the transaction was created "
          - name: year
            description: "Year when the transaction was created "
          - name: week_num
            description: "Week num when the transaction was created "
          - name: dayname
            description: "Day of the week when the transaction was created "
          - name: day_of_week
            description: "Day of the week when the transaction was created "
          - name: days_of_month
            description: "The days in a month on a given transaction date"
          - name: country_code
            description: "The two-character ISO country code of the card."
          - name: currency_code
            description: "The two-character ISO country code of the card."
          - name: external_ref
            description: "The card expiry year. Format: 4 digits. For example: 2020"
            tests: [ not_null ,unique ]
          - name: status
            description: "It is not specified in the API documentation, it always comes TRUE"
          - name: source
            description: "Name of the payment platform, indicates the source that in this source will be GlobePay by default"
          - name: ref
            description: "reference or unique identifier generated by a payment gateway in a specific event."
          - name: state
            description: "The binary state of the transaction. For example: Accepted or Declined."
          - name: cvv_provided
            description: "Boolean value that checks if the cvv was given in the transaction"

          - name: amount_lc
            description: "The amount that has been charged from the card."
          - name: amount_usd
            description: "The amount that has been charged from the card converted to usd according the conversion rate of the transaction"
          - name: chargeback_status
            description: "Description of chargeback_status column"
          - name: chargeback_source
            description: "Name of the payment platform, indicates the source that in this source will be GlobePay by default"
          - name: is_chargeback
            description: "Dispute of transaction made in your account and ask your financial institution to reverse the corresponding charge to the merchant or service provider"
          - name: updated_at
            description: "Timestamp when this model was updated"
    
